linters:
  enable-all: true

  disable:
    - depguard         # No need to have an allow-list of dependencies.
    - exhaustruct      # Frequently wrong, especially or url.URL and builder patterns.
    - gochecknoglobals # Useful for DefaultBaseURL.
    - tagliatelle      # Incorrect with OpenAI JSON payloads.
    - varnamelen       # I like single-character vars sometimes.
    # Deprecated:
    - deadcode
    - exhaustivestruct
    - ifshort
    - interfacer
    - golint
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
  - path: "^.+_test.go$"
    text: "add-constant: "

linters-settings:
  revive:
    enable-all-rules: true

    rules:
      - name: add-constant
        arguments:
          allowStrs: "\"\""

      - name: argument-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true